release: Mark-Island 0.2.37
Signed-off-by: fairapps <fairapps@appfair.net>

diff --git a/.github/workflows/fairground.yml b/.github/workflows/fairground.yml
--- a/.github/workflows/fairground.yml
+++ b/.github/workflows/fairground.yml
@@ -359,24 +359,22 @@ jobs:
         with:
           path: staging
 
-
-      - name: "Download ReleaseArtifacts"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release download --repo=${{ env.ORGNAME }}/App --dir UNTRUSTED -- "${{ steps.get_app_version.outputs.app_version }}" \
-                                                                                            || (sleep 60 && gh release download --repo=${{ env.ORGNAME }}/App --dir UNTRUSTED -- "${{ steps.get_app_version.outputs.app_version }}" ) \
-                                                                                            || (sleep 60 && gh release download --repo=${{ env.ORGNAME }}/App --dir UNTRUSTED -- "${{ steps.get_app_version.outputs.app_version }}" ) \
-                                                                                            || (sleep 60 && gh release download --repo=${{ env.ORGNAME }}/App --dir UNTRUSTED -- "${{ steps.get_app_version.outputs.app_version }}" ) 
-
-
       # compare the contents of the PR's un-trusted artifacts with
       # the contents of the base fair-ground's trusted artifacts
       - name: "Generate fairseal"
         env:
           GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
         run: |
-          mkdir -p fairseal/extracts/macOS/
+          # where we place the untrusted artifact
+          mkdir -p UNTRUSTED/
+
+          # build the URL for the GitHub download artifact
+          ZIPURL="https://github.com/${{ env.ORGNAME }}/App/releases/download/${{ steps.get_app_version.outputs.app_version }}/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" 
+
+          echo "Downloading: $ZIPURL"
+
+          # retry a few times in case the head repository is still building
+          curl --retry 10 --retry-all-errors -fsSL -o "UNTRUSTED/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" "$ZIPURL"
 
           ls -la "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" 
           ditto -xk "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" fairseal/extracts/macOS/trusted/
@@ -389,18 +387,16 @@ jobs:
 
           # check that contents are identical, first excising
           # signatures to permit custom signing & notarization
-          # find fairseal/extracts/macOS/trusted fairseal/extracts/macOS/UNTRUSTED -name _CodeSignature -type d -exec rm -r "{}" \;
-          diff -r fairseal/extracts/macOS/trusted fairseal/extracts/macOS/UNTRUSTED 
-          #|| echo "WARNING: contents differ"
+          # the actual diffing will be done by the fairtool; this is just for diagnostics
+          diff -r fairseal/extracts/macOS/trusted fairseal/extracts/macOS/UNTRUSTED || echo "WARNING: contents differ"
 
-          ZIPSHA=$(shasum -a 256 "UNTRUSTED/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" | cut -f 1 -d ' ')
 
           # if the seals match, we indicate success by publishing
           # the SHA256 for the release's pull request;
           # client apps will use this hash to verify that the untrusted
           # release artifact that is downloaded matches the release
           # artifact that was created in the trusted environment
-          echo xcrun swift run -- fairtool fairseal --sha256 "${ZIPSHA}" --verbose true --hub github.com/appfair --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --token "${{ secrets.GITHUB_TOKEN }}" --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" --untrusted-artifact "UNTRUSTED/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" -o -
+          xcrun swift run -- fairtool fairseal --verbose true --hub github.com/appfair --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" --untrusted-artifact "UNTRUSTED/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip" --artifact-url "$ZIPURL" --project . -o -
 
       - name: "Publish App Fair Catalog"
         env:
